### ISSUE TITLE
Debug and fix metrics_latest(last_checked_event.to_u64_digits()[0] out of index issue

### ISSUE THREAD

**Issue by dzmitryhil** [onomyprotocol/cosmos-gravity-bridge#41]
For some reason, the code on the main_loop.rs crashes with out of index exception. 
```
       last_checked_event = nonces.event_nonce;
                        if !last_checked_event.to_u64_digits().is_empty() {
                            metrics_latest(
                                last_checked_event.to_u64_digits()[0],
                                "last_checked_event",
                            );
                        }
```
[Our repo link](https://github.com/onomyprotocol/cosmos-gravity-bridge/blob/main/orchestrator/orchestrator/src/main_loop.rs#L217)
so we need to understand it and fix it because the original code doesn't have this and works properly [Gravity repo link.](https://github.com/gravity-bridge/gravity-bridge/blob/main/orchestrator/orchestrator/src/main_loop.rs#L209)

**Comment by AaronKutch** [comment]
it's happening when the number of events is zero, in which case `to_u64_digits` has length 0. It can be fixed with `*last_checked_event.to_u64_digits().get(0).unwrap_or(0)`.

**Comment by dzmitryhil** [comment]
> it's happening when the number of events is zero, in which case `to_u64_digits` has length 0. It can be fixed with `*last_checked_event.to_u64_digits().get(0).unwrap_or(0)`.

The problem is that on the original repo it is never 0. Which meant that our code works differently, and I would like to know why. Because expect it to work the same.

**Comment by dzmitryhil** [comment]
That is the question :-) We need to understand whether it can be 0 or not because on the original repo side it is never 0.

**Comment by AaronKutch** [comment]
this can be closed now
